/**
 * @file Source3DBallMesh.hpp
 * @brief Pass-13a (axis-1b foundation) DMPlex mesh container for the
 *        3D source ball. Reads TetGen .node / .ele files on rank 0,
 *        constructs an interpolated DMPlex, distributes across MPI
 *        ranks via DMPlexDistribute, and preserves per-vertex marker
 *        values for downstream surface labeling (pass-13c).
 *
 * Architecture notes:
 *  - The C++ runtime never invokes TetGen. The mesh files are
 *    pre-generated by tools/mesh_generation/build_source_ball_mesh.py
 *    and consumed here.
 *  - DMPlex construction matches the GmshIO.cpp pattern in this
 *    project: rank 0 owns the cell-vertex list, other ranks pass
 *    empty arrays, then DMPlexDistribute partitions.
 *  - Pass-12 parallel KSP fix (bjacobi+sub_lu) is not exercised here
 *    because pass-13a does not yet solve any system on the 3D mesh.
 *    Pass-13b (radiation diffusion) and pass-13c (constitutive update)
 *    will hook into the existing parallel KSP convention.
 *  - Per-vertex markers from the TetGen .node file are carried into a
 *    DMLabel ("SourceBallVertexMarker") so pass-13c can classify
 *    boundary facets into CAVITY_SURFACE vs ELASTIC_SURFACE without
 *    re-reading the mesh file. Pass-13a does not do that
 *    classification yet; the foundation slice only validates that the
 *    label survives DMPlexDistribute.
 *
 * References:
 *  - Si, H. (2015), "TetGen, a Delaunay-based quality tetrahedral mesh
 *    generator", ACM Trans. Math. Software 41(2), Article 11.
 *  - PETSc 3.25 manual, "DMPlex" chapter.
 */

#ifndef NEAR_FIELD_SOURCE_3D_BALL_MESH_HPP
#define NEAR_FIELD_SOURCE_3D_BALL_MESH_HPP

#include <petscdmplex.h>
#include <petscdmlabel.h>

#include <string>
#include <vector>

namespace FSRM {

/// Per-vertex marker convention emitted by build_source_ball_mesh.py.
/// Matches the marker semantics in tools/mesh_generation/README.md.
namespace SourceBallVertexMarkerValues {
constexpr int INTERIOR = 0;
constexpr int OUTER_ELASTIC_SURFACE = 1;
constexpr int INNER_CAVITY_SURFACE = 2;
}  // namespace SourceBallVertexMarkerValues

/// Name of the DMLabel that carries TetGen .node markers across
/// DMPlexDistribute. Pass-13c reads this label when building the
/// surface-integral extraction set.
constexpr const char* kSourceBallVertexMarkerLabel = "SourceBallVertexMarker";

/**
 * @brief DMPlex container for the axis-1b 3D source-ball mesh.
 *
 * Lifecycle:
 *  1. Construct (no DM yet).
 *  2. Call loadFromTetGen(comm, basename). On rank 0 this reads
 *     basename.node and basename.ele, builds an interpolated
 *     tetrahedral DMPlex, and distributes via DMPlexDistribute. On
 *     other ranks this constructs an empty DMPlex and receives its
 *     partition during distribution.
 *  3. Query numLocalCells / getDM / etc.
 *  4. Destruction releases the DM.
 *
 * Threading: not thread safe. One instance per source-ball solver.
 */
class Source3DBallMesh
{
public:
    Source3DBallMesh();
    ~Source3DBallMesh();

    Source3DBallMesh(const Source3DBallMesh&) = delete;
    Source3DBallMesh& operator=(const Source3DBallMesh&) = delete;
    Source3DBallMesh(Source3DBallMesh&&) = delete;
    Source3DBallMesh& operator=(Source3DBallMesh&&) = delete;

    /**
     * @brief Read TetGen .node / .ele on rank 0, build DMPlex,
     *        distribute across the communicator.
     *
     * @param comm     MPI communicator the DM will live on.
     * @param basename Path *without* extension. The function reads
     *                 basename + ".node" and basename + ".ele".
     *
     * Throws std::runtime_error if the files cannot be opened or
     * parsed, or if PETSc returns a non-zero error code.
     *
     * After return: getDM() is valid, numLocalCells / numGlobalCells
     * are populated, and the per-vertex marker label is attached.
     */
    void loadFromTetGen(MPI_Comm comm, const std::string& basename);

    /// Number of cells owned exclusively by this rank (overlap=0).
    PetscInt numLocalCells() const { return num_local_cells_; }

    /// Total number of cells across all ranks. Same on every rank.
    PetscInt numGlobalCells() const { return num_global_cells_; }

    /// Number of vertices visible on this rank's DM (includes cone
    /// closures of locally owned cells; does not include ghost
    /// overlap because we distribute with overlap=0).
    PetscInt numLocalVertices() const { return num_local_vertices_; }

    /// PETSc DMPlex handle. The Source3DBallMesh owns this and
    /// destroys it in the destructor; callers must not call
    /// DMDestroy() on it.
    DM getDM() const { return dm_; }

    /// MPI communicator the DM was created on.
    MPI_Comm getComm() const { return comm_; }

    /// Diagnostic basename of the loaded mesh files.
    const std::string& sourcePath() const { return source_basename_; }

    /// DMLabel that carries the per-vertex markers from the TetGen
    /// .node file. May be nullptr if no markers were present in the
    /// file. Caller does not own the label.
    DMLabel getVertexMarkerLabel() const { return vertex_marker_label_; }

    /// Min vertex distance from the origin among locally visible
    /// vertices. Pass-13a uses this only for sanity checks; pass-13c
    /// will replace this with a proper cavity-radius diagnostic.
    double localMinVertexRadius() const { return local_min_radius_; }

    /// Max vertex distance from the origin among locally visible
    /// vertices. Sanity check for the elastic-radius outer boundary.
    double localMaxVertexRadius() const { return local_max_radius_; }

    /// Count of local vertices flagged as INNER_CAVITY_SURFACE in the
    /// marker label. Pass-13c uses this to verify the cavity surface
    /// is non-empty before computing the surface integral.
    PetscInt numCavityMarkedVertices() const
    { return num_cavity_marked_vertices_; }

    /// Count of local vertices flagged as OUTER_ELASTIC_SURFACE.
    PetscInt numElasticMarkedVertices() const
    { return num_elastic_marked_vertices_; }

private:
    MPI_Comm comm_ = MPI_COMM_NULL;
    DM dm_ = nullptr;
    DMLabel vertex_marker_label_ = nullptr;
    PetscInt num_local_cells_ = 0;
    PetscInt num_global_cells_ = 0;
    PetscInt num_local_vertices_ = 0;
    PetscInt num_cavity_marked_vertices_ = 0;
    PetscInt num_elastic_marked_vertices_ = 0;
    std::string source_basename_;
    double local_min_radius_ = 0.0;
    double local_max_radius_ = 0.0;
};

}  // namespace FSRM

#endif  // NEAR_FIELD_SOURCE_3D_BALL_MESH_HPP
